create sequence hibernate_sequence start with 1 increment by 1;


create table book_users (book_id bigint not null, users varchar(255));
create table books (id bigint generated by default as identity, author varchar(128) not null, course varchar(128) not null, title varchar(128) not null, primary key (id));
create table messages (id bigint generated by default as identity, date timestamp not null, receiver varchar(128) not null, sender varchar(128) not null, text varchar(4096) not null, primary key (id));
create table user_roles (user_email varchar(255) not null, roles varchar(255));
create table users (email varchar(255) not null, enabled boolean not null, firstname varchar(255) not null, password varchar(255) not null, surname varchar(255) not null, primary key (email));
alter table books add constraint UK_5mtto2jcmfrwfg0p1ui8mnweu unique (title);
alter table book_users add constraint FKfjyy4j9xba2gpckps0pw0ukvo foreign key (book_id) references books;
alter table user_roles add constraint FK2052f4hqjgosti3i4ktlemi88 foreign key (user_email) references users;